#!/bin/bash
echo "======================="
echo "Name?  "
echo "======================="
read name
mkdir $name
mkdir $name/control
mkdir $name/pkgroot
mkdir $name/pkgroot/usr
touch $name/control/control
echo "Name: $name" > $name/control/control
echo "======================="
echo "Version?  "
echo "======================="
read ver
echo "Version: $ver" >> $name/control/control
echo "======================="
echo "Dep?"
echo "======================="
read deps
echo "Depends: $deps" >> $name/control/control
echo "======================="
echo "OK DONE"
echo "-----------------------"
echo "Dir Tree: "
echo "======================="
tree $name
echo "======================="
echo "Control File: "
echo "======================="
cat $name/control/control
